# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_login(object):
    def setupUi(self, form_login):
        form_login.setObjectName("form_login")
        form_login.resize(250, 120)
        form_login.setMinimumSize(QtCore.QSize(250, 120))
        form_login.setMaximumSize(QtCore.QSize(250, 120))
        self.verticalLayout = QtWidgets.QVBoxLayout(form_login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(form_login)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.user_label = QtWidgets.QLabel(self.widget)
        self.user_label.setObjectName("user_label")
        self.gridLayout.addWidget(self.user_label, 0, 0, 1, 1)
        self.user_input = QtWidgets.QLineEdit(self.widget)
        self.user_input.setObjectName("user_input")
        self.gridLayout.addWidget(self.user_input, 0, 1, 1, 1)
        self.pass_label = QtWidgets.QLabel(self.widget)
        self.pass_label.setObjectName("pass_label")
        self.gridLayout.addWidget(self.pass_label, 1, 0, 1, 1)
        self.pass_input = QtWidgets.QLineEdit(self.widget)
        self.pass_input.setObjectName("pass_input")
        self.gridLayout.addWidget(self.pass_input, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.btn_login = QtWidgets.QPushButton(form_login)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(form_login)
        QtCore.QMetaObject.connectSlotsByName(form_login)

    def retranslateUi(self, form_login):
        _translate = QtCore.QCoreApplication.translate
        form_login.setWindowTitle(_translate("form_login", "Form"))
        self.user_label.setText(_translate("form_login", "Username"))
        self.pass_label.setText(_translate("form_login", "Password"))
        self.btn_login.setText(_translate("form_login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_login = QtWidgets.QWidget()
    ui = Ui_form_login()
    ui.setupUi(form_login)
    form_login.show()
    sys.exit(app.exec_())
